// This file is auto-generated by Ultraviolet during npm install.
// It will be replaced when you run: npm install && npm start
// See: https://github.com/titaniumnetwork-dev/Ultraviolet

self.__uv$config = {
  prefix: "/service/",
  encodeUrl: (url) => encodeURIComponent(url),
  decodeUrl: (url) => decodeURIComponent(url),
  handler: "/assets/js/uv/uv.handler.js",
  client: "/assets/js/uv/uv.client.js",
  bundle: "/assets/js/uv/uv.bundle.js",
  config: "/assets/js/uv/uv.config.js",
  sw: "/assets/js/uv/uv.sw.js",
};
